<a href="https://colab.research.google.com/github/Danigol13/Exemplo-git/blob/main/1TDSS_NOITE_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introdução ao Numpy**

Na aula de hoje veremos como trabalhar com as funções do *Numpy*


In [2]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
kms = np.loadtxt(fname='carros-km.txt',dtype=int)
kms

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [7]:
kms.dtype

dtype('int64')

In [8]:
kms.shape

(258,)

In [15]:

carro1 = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
carro2 = ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
carro3 = ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']

dados = [
         carro1,
         carro2,
         carro3
]

dados

[(['Rodas de liga',
   'Travas elétricas',
   'Piloto automático',
   'Bancos de couro',
   'Ar condicionado',
   'Sensor de estacionamento',
   'Sensor crepuscular',
   'Sensor de chuva'],),
 (['Central multimídia',
   'Teto panorâmico',
   'Freios ABS',
   '4 X 4',
   'Painel digital',
   'Piloto automático',
   'Bancos de couro',
   'Câmera de estacionamento'],),
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [50]:
np_array = np.arange(1000000)
py_array = list(range(1000000))

In [20]:
%time for _ in range(100): np_array *= 2

CPU times: user 59.8 ms, sys: 1.84 ms, total: 61.7 ms
Wall time: 64.2 ms


In [51]:
%time for _ in range(100): py_array = [x * 2 for x in py_array]

CPU times: user 9.76 s, sys: 1.22 s, total: 11 s
Wall time: 11 s


In [54]:
numeros_np = np.arange(10)
numeros_py = list(range(10))

numeros_np *= 2
numeros_py = list(range(10))

print(numeros_np)
print(numeros_py)


[ 0  2  4  6  8 10 12 14 16 18]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [45]:
import python_utils as py

In [46]:
import pydata_google_auth as py

In [55]:
numeros_np.mean()


9.0

In [59]:
np.median(numeros_np)

9.0

In [60]:
np.std(np_array)

288675.1345946685

In [64]:
from random import randint
idades = np.array([ randint(20,60) for _ in range(100)])
idades

array([42, 46, 30, 46, 59, 57, 35, 42, 32, 31, 24, 46, 37, 30, 35, 48, 45,
       53, 28, 55, 48, 20, 57, 45, 25, 60, 24, 57, 55, 52, 56, 34, 32, 36,
       54, 57, 39, 27, 53, 46, 45, 51, 24, 48, 30, 31, 55, 58, 40, 27, 54,
       59, 44, 42, 35, 46, 44, 45, 46, 38, 39, 50, 57, 43, 31, 27, 30, 56,
       55, 47, 38, 60, 38, 51, 55, 44, 59, 30, 47, 33, 34, 27, 50, 59, 44,
       47, 37, 59, 49, 23, 22, 39, 39, 48, 47, 36, 58, 36, 48, 44])

In [65]:
cv = np.std(idades) / np.mean(idades)
cv


0.2524702917026479

In [67]:
  np.mean(idades)

42.96

In [68]:
np.median(idades)

44.5